server:
  port: 8089

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/dasiel/Documents/Spring Cloud/CODE/config-server-local-bundle/config-repo/configs
          search-paths: configs
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info
