server:
  port: 8088

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      # Enable service discovery (Eureka) integration at the gateway
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      httpclient:
        connect-timeout: 1000       # ms
        responseTimeout: 3s         # global response timeout

      routes:
        # ----------------- Flights Route -----------------
        - id: flights
          uri: lb://flight-search-service         # Use load-balanced discovery to route to the service
          predicates:
            - Path=/api/flights/**                # Match incoming requests starting with /api/flights/
          filters:
            - name: Retry
              args:
                retries: 1
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: flightsEdgeCB
                fallbackUri: forward:/fallback/flights
          metadata:
            connect-timeout: 800     # ms
            response-timeout: 2500   # ms

        # ----------------- Bookings Route -----------------
        - id: bookings
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - name: Retry
              args:
                retries: 1
                methods: POST,GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: bookingsEdgeCB
                fallbackUri: forward:/fallback/bookings
          metadata:
            connect-timeout: 1000    # ms
            response-timeout: 5000   # ms (bookings may take longer)

        # ----------------- Pricing Route -----------------
        - id: pricing
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**
          filters:
            - name: Retry
              args:
                retries: 1
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: pricingEdgeCB
                fallbackUri: forward:/fallback/pricing
          metadata:
            connect-timeout: 600     # ms
            response-timeout: 2000   # ms (aggressive for pricing)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,refresh,env
