server:
  port: 8080

spring:
  application:
    name: flight-search-service
  datasource:
    url: jdbc:postgresql://localhost:5432/flights
    username: flight
    password: flight
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
