server:
  port: 8088

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        responseTimeout: 3s
      routes:
        - id: flights
          uri: lb://flight-search-service
          predicates: [ Path=/api/flights/** ]
        - id: pricing
          uri: lb://pricing-service
          predicates: [ Path=/api/pricing/** ]
        - id: bookings
          uri: lb://booking-service
          predicates: [ Path=/api/bookings/** ]
