server:
  port: 9080

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5433/bookingsdb
    username: bookings
    password: bookings
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
