global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'host.docker.internal:8080'   # flight-search
          - 'host.docker.internal:8081'   # pricing
          - 'host.docker.internal:8082'   # booking
          - 'host.docker.internal:8088'   # api-gateway