server:
  http_listen_port: 9081

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: spring-microservices
    static_configs:
      - targets: [localhost]
        labels:
          job: spring-microservices
          app: flight-search-service
          __path__: /var/log/services/flight-search-service/logs/*.log
      - targets: [localhost]
        labels:
          job: spring-microservices
          app: pricing-service
          __path__: /var/log/services/pricing-service/logs/*.log
      - targets: [localhost]
        labels:
          job: spring-microservices
          app: booking-service
          __path__: /var/log/services/booking-service/logs/*.log
      - targets: [localhost]
        labels:
          job: spring-microservices
          app: api-gateway
          __path__: /var/log/services/api-gateway/logs/*.log
